#!/bin/sh

[ -d $HOME/.bin ] && export PATH="$HOME/.bin:$PATH"

export PAGER="less"
export LESS="-R "
export EDITOR="nvim"
export BROWSER="firefox"
export FZF_DEFAULT_COMMAND='
  (git ls-files . -co --exclude-standard ||
   find . -path "*/\.*" -prune -o -type f -print -o -type l -print |
      sed s/^..//) 2> /dev/null'

# Machine-specific customizations
[[ -r $HOME/.profile.local ]] && source $HOME/.profile.local
