#!/bin/sh

export PAGER="less"
export LESS="-R "
export EDITOR="nvim"
export KUBE_EDITOR="nvim"
export K9S_CONFIG_DIR="$HOME/.config/k9s"
export BROWSER="firefox"
export FZF_DEFAULT_COMMAND='
  (git ls-files . -co --exclude-standard ||
   find . -path "*/\.*" -prune -o -type f -print -o -type l -print |
      sed s/^..//) 2> /dev/null'

# Machine-specific customizations
[[ -r $HOME/.profile.local ]] && source $HOME/.profile.local
