#!/bin/sh

export PAGER="less"
export LESS="-R "
export EDITOR="nvim"
export BROWSER="firefox"
export FZF_DEFAULT_COMMAND='
  (git ls-files . -co --exclude-standard ||
   find . -path "*/\.*" -prune -o -type f -print -o -type l -print |
      sed s/^..//) 2> /dev/null'

# git-config env-specific values
export GIT_CONFIG_COUNT=2
export GIT_CONFIG_KEY_0="user.email"
export GIT_CONFIG_VALUE_0="brandon.waskiewicz@gmail.com"
export GIT_CONFIG_KEY_1="core.excludesfile"
export GIT_CONFIG_VALUE_1="$HOME/.gitignore"

# Machine-specific customizations
[[ -r $HOME/.profile.local ]] && source $HOME/.profile.local
