#!/bin/sh
#
# ~/.xprofile
#

if [ -x /usr/bin/numlockx ]; then
	/usr/bin/numlockx on
fi

if [ -d ~/.fonts ]; then
	xset +fp ~/.fonts
fi
if [ -d ~/.local/share/fonts ]; then
	xset +fp ~/.local/share/fonts
fi
if [ -e ~/.xbindkeysrc ]; then
	xbindkeys
fi
xset +fp /usr/share/fonts/local
xset fp rehash
xsetroot -cursor_name left_ptr
xset r rate 250 20
xset +dpms
xset dpms 0 0 300

#autocutsel -fork &
#autocutsel -selection PRIMARY -fork &

xautolock -time 10 -locker slock -detectsleep &
devmon &
