[[profile]]
name = "docked"
exec = ["notify-send shikane \"Profile '$SHIKANE_PROFILE_NAME' has been applied\""]

    [[profile.output]]
    enable = true
    search = ["m=DELL U2412M", "s=M2GCR288268L", "v=Dell Inc."]
    mode = "1920x1200@59.95Hz"
    position = "-1920,-1200"
    scale = 1.0
    transform = "normal"
    adaptive_sync = false

    [[profile.output]]
    enable = true
    search = ["m=LG HDR 4K", "s=0x0001806F", "v=LG Electronics"]
    mode = "3840x2160@60Hz"
    position = "0,-2160"
    scale = 1.0
    transform = "normal"
    adaptive_sync = false

    [[profile.output]]
    enable = true
    search = ["m=0x0791", "s=", "v=BOE"]
    mode = "1920x1080@60.012Hz"
    position = "0,0"
    scale = 1.0
    transform = "normal"
    adaptive_sync = false

[[profile]]
name = "mobile"
exec = ["notify-send shikane \"Profile '$SHIKANE_PROFILE_NAME' has been applied\""]
    [[profile.output]]
    enable = true
    search = ["m=0x0791", "s=", "v=BOE"]
    mode = "1920x1080@60.012Hz"
    position = "0,0"
    scale = 1.0
    transform = "normal"
    adaptive_sync = false
